services:
  psytest:
    build: .
    image: psytest:latest
    container_name: psytest
    restart: unless-stopped
    networks: [tsnet]
    user: "65532:65532"
#    ports:
#      - "8080:8080"
    environment:
      # - APP_BASE_URL=/psytest
      - APP_MAX_FILE_SIZE_MB=1 # Example: Set max file size to 1 MB
      # - APP_UPLOAD_FOLDER=/app/uploads
      # - APP_DOMAIN=example.com
    volumes:
      - psytest_data:/app/uploads
      #use `docker compose cp psytest:/app/uploads ./uploads` to download data to dir

volumes:
  psytest_data:
networks:
  tsnet:
    external: true